apps/usuarios/urls.py
from django.urls import path, re_path

from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.UsuariosView.as_view(), name="listar"),
    path('crear/', views.CrearUsuarioView.as_view(), name="crear"),
    re_path('(?P<pk>\d+)/modificar/', views.ModificarUsuarioView.as_view(), name="modificar"),
    re_path('(?P<pk>\d+)/desactivar/', views.DesactivarUsuarioView.as_view(), name="desactivar"),
]

fukuroo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('apps.usuarios.urls', namespace='usuarios')),
]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return '%s' % self.get_full_name()

apps/usuarios/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm
from apps.usuarios.models import Usuario
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin

class CreateUserForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = Usuario
        fields = [
            'username',
            'last_name',
            'first_name',
            'email',
            'password1',
            'password2',
        ]
        error_messages = {
            'username': {'unique': 'No puede utilizar este Nombre de usuario.'},
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control input'})

class UpdateUserForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [
            'username',
            'last_name',
            'first_name',
            'email',
        ]
        error_messages = {
            'username': {'unique': 'No puede utilizar este Nombre de usuario.'},
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control input'})

class UserBajaLogicaForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Usuario
        fields = []

apps/usuarios/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from apps.usuarios.models import Usuario
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView, UpdateView
from apps.usuarios import forms

class UsuariosView(ListView):
    model = Usuario
    template_name = 'usuarios.html'

class CrearUsuarioView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Usuario
    form_class = forms.CreateUserForm
    template_name =  'agregar_modificar_modal_columnas.html'
    success_url = reverse_lazy('usuarios:listar')
    success_message = 'Datos guardados exitosamente.'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['title'] = 'Agregar Usuario'
        return contexto
        
    def form_valid(self, form):
        usuario = form.save(commit=False)
        usuario.is_staff = True
        usuario.is_superuser = True
        return super().form_valid(form)

class ModificarUsuarioView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Usuario
    form_class = forms.UpdateUserForm
    template_name = 'agregar_modificar_modal_columnas.html'
    success_url = reverse_lazy('usuarios:listar')
    success_message = 'Datos guardados exitosamente.'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['title'] = 'Modificar Usuario'
        return contexto

class DesactivarUsuarioView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Usuario
    form_class = forms.UserBajaLogicaForm
    template_name = 'eliminar_modal.html'
    success_message = 'Usuario desactivado exitosamente.'
    success_url =  reverse_lazy('usuarios:listar')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['modelo_nombre'] = 'Usuario'
        return contexto

    def form_valid(self, form):
        usuario = form.save(commit=False)
        usuario.is_active = False
        return super().form_valid(form)

apps/usuarios/templates/usuarios.html
{% extends 'base.html' %}
{% block titulo %} Usuarios {% endblock %}

{% block contenido %}
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h3>Usuarios del sistema</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2 pull-right">
			<button class="agregar-modal btn btn-primary btn-sm" type="button" name="button">Agregar</button>
		</div>
	</div>
	<table class='table'>
		<thead>
			<th>Usuario</th>
			<th>Apellido</th>
			<th>Nombre</th>
			<th>Email</th>
			<th></th>
		</thead>
		<tbody>
			{% for user in object_list%}
				{% if not user.is_superuser and user.is_active %}
					<tr>
						<td>{{user.username}}</td>
						<td>{{user.last_name}}</td>
						<td>{{user.first_name}}</td>
						<td>{{user.email}}</td>
						<td>
							<a class="modificar-modal accion" title="Modificar Usuario" data-id="{% url 'usuarios:modificar' user.id %}">
                            <i class="glyphicon glyphicon glyphicon-edit"></i></a>
                            
                            <a class="eliminar-modal accion text-danger" title="Desactivar Usuario" data-id="{% url 'usuarios:desactivar' user.id %}">
                            <i class="glyphicon glyphicon-remove"></i></a>
                        </td>
					</tr>
				{% endif %}
			{% endfor %}
		</tbody>
	</table>
</div>

{% include "modal.html" %}

{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {

    $(".agregar-modal").modalForm({
        formURL: "{% url 'usuarios:crear' %}"
    });

	$(".modificar-modal").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
    });

	$(".eliminar-modal").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
    });

});
</script>
{% endblock %}

templates/agregar_modificar_modal_columnas.html
<form id="modal-form" method="post" action="">
  {% csrf_token %}

 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  <h3 class="modal-title">{{title}}</h3>
  </div>

  <div class="modal-body">
    {% for field in form %}    
        {% if forloop.first %}
        <div class="row align-items-center">
        {% endif %}
        <div class="col-sm-6">
            <div class="form-group{% if field.errors %} invalid has-error {% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
          </div>
        </div>
        {% if forloop.last %}
            </div>
        {% else %}
            {% if forloop.counter|divisibleby:'2' %}
                </div>
                <div class="row align-items-center">
            {% endif %}
        {% endif %}    
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" id="btn-g" class="submit-btn btn btn-primary">Guardar</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  </div>

</form>

<script>
$( "#modal-form" ).submit(function( event ) {
  document.getElementById("btn-g").click();
});
</script>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block titulo %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/estilos-base.css' %}">
    {% block css%}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</head>
<body>
    <header>
        <nav class="main-navbar navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">                    
                    <a href="/" class="navbar-brand" title="Ir a pagina principal">Usuarios</a>
                </div>
                {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navbar-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">{{ user.get_full_name}}</a></li>
                        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Salir</a></li>
                    </ul>
                </div>
                {% else %}
                <div class="collapse navbar-collapse" id="navbar-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Ingresar</a></li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </nav>
    </header>

    {% include 'messages.html'%}
    {% block contenido %}
    {% endblock %}

</body>
</html>

templates/eliminar_modal.html
<form method="post" action=""> {% csrf_token %}

 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  <h3 class="modal-title">Eliminar {{modelo_nombre}}</h3>
  </div>

  <div class="modal-body">
    <p>¿Esta seguro de que quiere eliminar {{modelo_nombre}}?</p>
  </div>

  <div class="modal-footer">
  <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
  </div>

</form>

templates/messages.html
{% if messages %}
	<div class="container">
		{% for message in messages %}
			{% if message.tags == 'success' %}
				<div class="alert alert-success alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true" title="Cerrar mensaje">&times;</span></button>
					{{message}} <i class="glyphicon glyphicon-ok-circle"></i>
				</div>
			{% elif message.tags == 'error'%}
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true" title="Cerrar mensaje">&times;</span></button>
					{{message}} <i class="glyphicon glyphicon-ok-circle"></i>
				</div>
			{% endif %}
		{% endfor %}
	</div>
{% endif %}

templates/modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>